name: CI Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: latest

      - name: Lint
        uses: golangci/golangci-lint-action@v4

      - name: Test
        run: go test -v ./...

      - name: Build
        run: CGO_ENABLED=0 go build -trimpath -ldflags="-w -s"
