name: CI Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'
          cache: false
      - name: Lint
        uses: golangci/golangci-lint-action@v4
      - name: Build
        run: CGO_ENABLED=0 go build -trimpath -ldflags="-w -s"
